### ISSUE TITLE
Make it private

### ISSUE THREAD

**Issue by aikikode** [silh/trakind#2]
Hi @silh,

I have a suggestion to remove this repo from public access.

The reason is that there're now many custom bots already doing not only time window search but also automatic registrations in IND. This repo is good for your own (and your friends) private use. But posting it publicly makes it firstly transparent to IND that there're automatic services doing such calls and secondly huge amount of people abusing this service. That can lead to IND put additional layers of protection against such bots (like captcha). And that will make none of such applications work, even this tool.

I suggest you to keep it for your private use. This way it won't generate too much traffic to IND and not bring too much attention.

**Comment by silh** [comment]
Stoping automatic registration would be a good thing - that would make it easier for people who are not aware of those bots be able to easier get their appointments. Maybe those bots are part of the problem we are in right now where?

**Comment by aikikode** [comment]
I don't think it will make life easier - there will still be bots working that are able to overcome those layers of protection, but it's just will be fewer of them. And those developers that don't manage to overcome captcha will have to do it manually then instead of using their private tools that won't work.

**Comment by silh** [comment]
@aikikode I only see how they can affect bots that do registration for you. If all it does is checks the time slots then it basically the same as if you were sitting there and refreshed the page. Hurting registration bots is desirable.

**Comment by aikikode** [comment]
Well, we can't be sure at what level captcha will be added: if they add it at the very first step, then even opening the calendar to look for a slot won't be possible automatically for most of the tools.

**Comment by silh** [comment]
Actually opening captcha on calendar page won't affect it. They would to add captcha on every value change - location, number of people.

**Comment by aikikode** [comment]
The problem is that the results of such calls that are used in the code, e.g.
https://oap.ind.nl/oap/api/desks/AM/slots/?productKey=DOC&persons=1
become obsolete several seconds after they appear, because they are booked by other existing automatic tools. So nobody is able to use this program to actually find the appropriate time slot to book for themselves.

AFAIS the only value of this application is to make IND aware of automatic tools that do slots search & bookings then?

**Comment by silh** [comment]
That already sounds like a positive outcome.

**Comment by RXWatcher** [comment]
I disagree on the need to make it private. I already forked it just in case :)

I was actually in the process of building my own using Apprise to allow it to communicate with 70+ messaging services (https://github.com/caronc/apprise) until someone pointed me here.

IND really needs to have a similar service. It's crazy that the only publicly known solution is to refresh a web page looking for appointments.
