### ISSUE TITLE
Biometrics appointment

### ISSUE THREAD

**Issue by schrau24** [silh/trakind#3]
Hi,

Thanks for this awesome bot! What additional work would be required to do a similar check of available biometric appointment slots? I don't have any experience with API bot interfacing. Would it simply be replacing the URL in the 'track' function?

**Comment by silh** [comment]
Hi,

Thank you for your interest, I was planning to add it here - https://github.com/silh/trakind/pull/4/files.

**Comment by silh** [comment]
Implemented in https://github.com/silh/trakind/pull/4

**Comment by schrau24** [comment]
Thanks this is awesome!
