### ISSUE TITLE
Fetcher receiving 403

### ISSUE THREAD

**Issue by Infonautica** [silh/trakind#5]
Hi, thanks for the work on the bot. Sadly fetcher receives a 403, so i suspect there were some unxpected API changes:

<img width="886" alt="Screenshot 2024-08-14 at 12 58 09" src="https://github.com/user-attachments/assets/c8e65ef0-3c39-4995-80fc-de4b76f7508b">

I'll take a deeper look later today

**Comment by silh** [comment]
Thanks for bringing this up. They seem to disallow the trailing slash now. Fixed it in this commit - https://github.com/silh/trakind/commit/7b23f7f1e82c9a2b26847a3dba93da4d3a71c0de

**Comment by leodnlv** [comment]
I can confirm everything is working now, thank you!
